### ISSUE TITLE
Subscription example code

### ISSUE THREAD

**Issue by RobertBrunhage** [pplante/flutter_payments#1]
Could you provide some more example code on how to implement subscription?

Having a hard time understanding this:

    List<Purchase> purchase = await FlutterPayments.purchase(sku: 'android.test.purchased', type: 
    ProductType.Subscription);

How do I check if I am subscribed? This returns a list och purchases. Shall I check if (pruchase[0].isActive)?

**Comment by pplante** [comment]
Check out the updated README.md section: https://github.com/pplante/flutter_payments#subscriptions
