### ISSUE TITLE
Build apk Junit Error

### ISSUE THREAD

**Issue by RobertBrunhage** [pplante/flutter_payments#2]
Getting this error when trying to build apk:

![image](https://user-images.githubusercontent.com/26344867/42449622-ac02da50-8381-11e8-82df-07dc5e71e19a.png)

What can I do to resolve this?

**Comment by pplante** [comment]
I am not sure why JUnit 5.0.0 disappeared, but I bumped this to 5.2.0.  Does the latest release compile for you?
